networks:
  phantom-zone:
    name: nana.phantom-zone.net

services:
  vscode:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nana.phantom-zone.vscode
    image: nana/phantom-zone/vscode
    networks:
      - phantom-zone 
    volumes:
      - type: bind
        source: ..
        target: /mnt

version: "3.8"
